[package]
name = "filecoin-proofs-api"
version = "6.0.0"
description = "API to interact with the proofs system in Filecoin"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nilfoundation/rust-filecoin-proofs-api"
readme = "README.md"

[dependencies]
anyhow = "1.0.26"
bincode = "1.1.2"
serde = "1.0.104"
filecoin-proofs-v1 = { package = "filecoin-proofs", git = "ssh://git@github.com/nilfoundation/rust-fil-proofs.git", branch = "master", default-features = false }
filecoin-hashers = { package = "filecoin-hashers", git = "ssh://git@github.com/nilfoundation/rust-fil-proofs.git", branch = "master", default-features = false, features = ["poseidon", "sha256"] }
filecoin-hashers = { package = "sds", git = "ssh://git@github.com/nilfoundation/rust-fil-proofs.git", branch = "master", default-features = false }
bellperson = { git = "ssh://git@github.com/nilfoundation/fil-zk.git", branch = "master", default-features = false }
rayon = "1.2.1"
rayon-core = "1.6.1"
rayon-futures = "0.1.1"

[features]
default = ["blst", "gpu"]
gpu = ["bellperson/gpu", "filecoin-proofs-v1/gpu"]
pairing = ["filecoin-proofs-v1/pairing", "bellperson/pairing"]
blst = ["filecoin-proofs-v1/blst", "bellperson/blst"]
